import './style.css';
import {analyze,DEFAULTS,PRESETS,report,importReport,SDK_VERSION,type Inputs,type Analysis} from './engine';
const money=(n:number,d=2)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:d,minimumFractionDigits:d}).format(n);
const compact=(n:number)=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(n);
const pct=(n:number)=>`${money(n)}%`;
const price=(n:number)=>n.toPrecision(5);
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let state={...DEFAULTS};let current:Analysis|null=null;let baseline:Analysis|null=null;
const fields:{key:keyof Inputs;label:string;unit:string;min:number;max:number;step?:number}[]=[
 {key:'supply',label:'Token supply',unit:'tokens',min:1000,max:1e12},
 {key:'initialFdv',label:'Initial FDV',unit:'USDC',min:10,max:1e9},
 {key:'migrationFdv',label:'Graduation FDV',unit:'USDC',min:11,max:1e10},
 {key:'startFeeBps',label:'Opening fee',unit:'bps',min:1,max:9900},
 {key:'endFeeBps',label:'Final fee',unit:'bps',min:1,max:9900},
 {key:'durationMinutes',label:'Fee decay duration',unit:'min',min:0,max:1440},
 {key:'lockedLpPercent',label:'Permanently locked LP',unit:'%',min:0,max:100},
];
document.querySelector('#app')!.innerHTML=`
<header><a class="brand" href="./"><img src="./favicon.svg" alt="" width="34" height="34">Curve<span>Scope</span></a><nav><a href="#lab" class="active">Curve lab</a><a href="#method">Methodology</a><a href="./pitch.html" target="_blank">Project brief ↗</a></nav><span class="status"><i></i> LOCAL SIMULATION</span></header>
<main><section class="hero"><div><p class="eyebrow">METEORA DBC / DEVELOPER TOOLING</p><h1>Know your curve.<br><span>Before you launch.</span></h1><p class="intro">Stress-test launch economics with the actual Meteora SDK.<br> Compare configurations. Understand the trade-offs. Export the evidence.</p></div><div class="hero-aside"><span class="orbit">⌁</span><p>DESIGN → QUOTE → VERIFY</p><span>USDC quote · 6 decimal tokens<br>DBC → DAMM v2</span></div></section>
<section class="preset-row" aria-label="Configuration presets">${PRESETS.map((p,j)=>`<button class="preset ${j===0?'chosen':''}" data-preset="${j}"><span class="preset-num">0${j+1}</span><span><b>${p.name}</b><small>${p.detail}</small></span><span class="arrow">↗</span></button>`).join('')}</section>
<section class="lab" id="lab"><aside class="config-panel"><div class="panel-heading"><h2>Launch configuration</h2><span class="tag">01</span></div><p class="muted">Edit assumptions to explore the result.</p><form id="config-form">${fields.map(f=>`<label for="${f.key}">${f.label}<div class="input-wrap"><input id="${f.key}" name="${f.key}" type="number" min="${f.min}" max="${f.max}" step="1" value="${state[f.key]}" required><span>${f.unit}</span></div></label>`).join('')}<div class="fixed-choices">IMMUTABLE TOKEN AUTHORITY<br>LINEAR FEE DECAY · DYNAMIC FEES OFF<br>DAMM V2 · 1% POST-MIGRATION FEE</div></form><div class="config-actions"><button id="pin" class="secondary">＋ Pin as baseline</button><button id="reset" class="text-button">Reset parameters</button></div></aside>
<div class="results"><div class="results-bar"><div><span class="eyebrow">CONFIGURATION REPORT</span><span id="valid-badge" class="valid">SDK validated</span></div><div class="tools"><button id="import" class="text-button">Import</button><button id="export" class="primary">Export report ↓</button><input id="file" type="file" accept="application/json,.json" hidden></div></div><p id="error" role="alert" hidden></p><div id="analysis"></div></div></section>
<section class="method" id="method"><div><p class="eyebrow">MODEL, NOT MARKET DATA</p><h2>Reproducible by design.</h2><p>Every point is a separate first buy into an empty virtual pool. Changing elapsed time evaluates the fee schedule while keeping that pool empty. The chart is not a forecast or a sequence of real trades.</p><a href="https://github.com/MeteoraAg/dynamic-bonding-curve-sdk" target="_blank" rel="noreferrer">Inspect the official SDK ↗</a></div><div class="method-steps"><article><span>01</span><div><h3>Build & validate</h3><p><code>buildCurveWithMarketCap</code> generates the DBC configuration. <code>validateConfigParameters</code> checks SDK constraints.</p></div></article><article><span>02</span><div><h3>Quote the boundary</h3><p><code>getQuoteFromInputAmount</code> with PartialFill accounts for fees, minimum output and unfilled USDC at graduation.</p></div></article><article><span>03</span><div><h3>Keep exact evidence</h3><p>JSON reports preserve SDK integer values as decimal strings, the SDK version and every assumption. Import reruns the calculation.</p></div></article></div></section>
<footer><span>CurveScope <small>v0.1 · SDK ${SDK_VERSION}</small></span><span>Offline model · No wallet required · No transactions</span><a href="./pitch.html">Built for Crypto World's Fair ↗</a></footer></main><div id="toast" role="status" hidden></div>`;
function svgChart(a:Analysis){
 const w=760,h=260,l=65,r=22,t=15,b=43;
 const plotBaseline=baseline?analyze({...baseline.inputs,elapsedMinutes:a.inputs.elapsedMinutes,slippageBps:a.inputs.slippageBps}):null;
 const curves=[a,...(plotBaseline?[plotBaseline]:[])];
 const maxX=Math.max(...curves.map(c=>c.threshold)),maxY=Math.max(...curves.flatMap(c=>c.points.map(p=>p.averagePrice)))*1.08;
 const x=(v:number)=>l+v/maxX*(w-l-r),y=(v:number)=>h-b-v/maxY*(h-t-b);
 const line=(c:Analysis)=>`M${x(0)},${y(c.initialPrice/(1-c.selected.fee/c.selected.used))} `+c.points.map(p=>`L${x(p.requested)},${y(p.averagePrice)}`).join(' ');
 const grid=Array.from({length:5},(_,i)=>{const yy=t+i*(h-t-b)/4,val=maxY*(1-i/4);return `<line x1="${l}" y1="${yy}" x2="${w-r}" y2="${yy}" stroke="#263333" stroke-dasharray="3 5"/><text x="${l-10}" y="${yy+4}" text-anchor="end">${val.toFixed(5)}</text>`;}).join('');
 const ticks=Array.from({length:5},(_,i)=>`<text x="${x(maxX*i/4)}" y="${h-19}" text-anchor="middle">${compact(maxX*i/4)}</text>`).join('');
 const selected=a.selected.requested<=maxX?`<circle cx="${x(a.selected.requested)}" cy="${y(a.selected.averagePrice)}" r="5" fill="#0b1112" stroke="#bafa68" stroke-width="3"/>`:'';
 return `<svg role="img" aria-label="Average first-buy execution price versus order size in USDC, with fees included" viewBox="0 0 ${w} ${h}"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#bafa68" stop-opacity=".16"/><stop offset="1" stop-color="#bafa68" stop-opacity="0"/></linearGradient></defs>${grid}${ticks}<path d="${line(a)} L${x(a.threshold)},${h-b} L${l},${h-b} Z" fill="url(#fill)"/>${baseline?`<path d="${line(plotBaseline!)}" fill="none" stroke="#8eacf7" stroke-width="2" stroke-dasharray="6 5"/>`:''}<path d="${line(a)}" fill="none" stroke="#bafa68" stroke-width="3"/>${selected}</svg>`;
}
function render(a:Analysis){
 const q=a.selected;
 document.querySelector('#analysis')!.innerHTML=`
 <div class="metrics"><article><span>GRADUATION RESERVE</span><strong>${compact(a.threshold)} <small>USDC</small></strong><p>Net quote reserve required by SDK</p></article><article><span>INITIAL TOKEN PRICE</span><strong>${price(a.initialPrice)} <small>USDC</small></strong><p>${compact(a.inputs.initialFdv)} initial fully diluted value</p></article><article><span>MIGRATED LIQUIDITY</span><strong>${a.inputs.lockedLpPercent}<small>% locked</small></strong><p>${100-a.inputs.lockedLpPercent}% withdrawable by creator</p></article></div>
 <article class="chart-card"><div class="chart-heading"><div><h2>First-buy execution curve</h2><p>Average price per token, including fees · USDC</p></div><div class="legend"><span><i></i> Current</span>${baseline?'<span><i class="base"></i> Baseline</span>':''}</div></div>${svgChart(a)}<div class="chart-bottom"><span>ORDER SIZE (USDC)</span><span>32 independent quotes · empty pool · ${a.inputs.elapsedMinutes} min</span></div></article>
 <article class="probe"><div class="panel-heading"><h2>Inspect a first buy</h2><span class="tag">02</span></div><div class="probe-inputs"><label for="buyAmount">Order size (USDC)<input id="buyAmount" name="buyAmount" form="config-form" type="number" min="0.000001" max="1000000000" step="0.000001" value="${a.inputs.buyAmount}"></label><label for="elapsedMinutes">Minutes after activation<input id="elapsedMinutes" name="elapsedMinutes" form="config-form" type="number" min="0" max="2880" step="1" value="${a.inputs.elapsedMinutes}"></label><label for="slippageBps">Slippage tolerance (bps)<input id="slippageBps" name="slippageBps" form="config-form" type="number" min="0" max="5000" step="1" value="${a.inputs.slippageBps}"></label><button id="apply-probe" class="secondary">Recalculate ↗</button></div><div class="quote-grid"><div><span>Tokens received</span><strong>${compact(q.output)}</strong><small>Minimum ${compact(q.minimumOutput)} at tolerance</small></div><div><span>Curve-only price impact</span><strong class="${q.curveImpactPct>10?'amber':''}">${pct(q.curveImpactPct)}</strong><small>Average net price vs initial spot</small></div><div><span>Trading fee</span><strong>${money(q.fee)} <small>USDC</small></strong><small>All-in cost vs spot: +${pct(q.costVsSpotPct)}</small></div><div><span>Unfilled at graduation</span><strong>${money(q.unfilled)} <small>USDC</small></strong><small>Modeled spend: ${money(q.used)} USDC</small></div></div></article>
 ${baseline?`<article class="comparison"><div><h3>Baseline comparison</h3><p>Both configurations quoted with the current order, time and tolerance.</p></div><button id="clear-baseline" class="text-button">Clear ×</button><div id="comparison-values"></div></article>`:''}
 <article class="stress-card"><div class="panel-heading"><div><h2>Where does the curve bend?</h2><p class="muted">Order sizes as a share of net graduation reserve.</p></div><span class="tag">03</span></div><div class="table-wrap"><table><thead><tr><th>Order / reserve</th><th>Input USDC</th><th>Tokens out</th><th>Curve impact</th><th>Unfilled USDC</th></tr></thead><tbody>${a.sizes.map((p,j)=>`<tr><td>${[1,5,10,25,50,100,150][j]}%</td><td>${money(p.requested)}</td><td>${compact(p.output)}</td><td class="${p.curveImpactPct>10?'amber':''}">${pct(p.curveImpactPct)}</td><td>${money(p.unfilled)}</td></tr>`).join('')}</tbody></table></div></article>
 <div class="bottom-grid"><article class="fee-card"><h2>Fee-window comparison</h2><p class="muted">Same first buy at three activation offsets.</p>${a.feeWindows.map(p=>`<div class="fee-row"><span>${p.minute} min</span><b>${money(p.fee)} USDC fee</b><span>${compact(p.output)} tokens</span></div>`).join('')}</article><article class="notes-card"><h2>Configuration observations</h2>${a.notes.length?a.notes.map(n=>`<p class="note">${esc(n)}</p>`).join(''):'<p class="note calm">No threshold warnings triggered by this order. SDK validity is not an audit or a prediction of launch success.</p>'}<p class="muted">No prior trades, dynamic fees, transfer fees, network fees or post-migration execution are modeled.</p></article></div>`;
 if(baseline){
   try{const comparable=analyze({...baseline.inputs,buyAmount:a.inputs.buyAmount,elapsedMinutes:a.inputs.elapsedMinutes,slippageBps:a.inputs.slippageBps});
    document.querySelector('#comparison-values')!.innerHTML=`<span>Tokens vs baseline <b>${q.output>=comparable.selected.output?'+':''}${pct((q.output/comparable.selected.output-1)*100)}</b></span><span>Fee difference <b>${money(q.fee-comparable.selected.fee)} USDC</b></span><span>Reserve difference <b>${money(a.threshold-comparable.threshold)} USDC</b></span>`;
   }catch{document.querySelector('#comparison-values')!.textContent='This baseline cannot quote the selected scenario.';}
 }
 document.querySelector('#apply-probe')?.addEventListener('click',readForm);
 document.querySelector('#clear-baseline')?.addEventListener('click',()=>{baseline=null;render(a);});
 for(const name of ['buyAmount','elapsedMinutes','slippageBps']){document.getElementById(name)?.addEventListener('change',readForm);document.getElementById(name)?.addEventListener('keydown',e=>{if((e as KeyboardEvent).key==='Enter'){e.preventDefault();readForm();}});}
}
function notify(message:string){const e=document.querySelector<HTMLElement>('#toast')!;e.textContent=message;e.hidden=false;setTimeout(()=>e.hidden=true,3500);}
function compute(){
 const error=document.querySelector<HTMLElement>('#error')!;
 try{current=analyze(state);error.hidden=true;document.querySelector('#valid-badge')!.textContent='SDK validated';document.querySelector('#analysis')!.removeAttribute('hidden');(document.querySelector('#export') as HTMLButtonElement).disabled=false;(document.querySelector('#pin') as HTMLButtonElement).disabled=false;render(current);}
 catch(e){current=null;error.textContent=e instanceof Error?e.message:String(e);error.hidden=false;document.querySelector('#valid-badge')!.textContent='Needs correction';document.querySelectorAll<HTMLElement>('#analysis > *').forEach(el=>{el.hidden=!el.classList.contains('probe');});document.querySelector<HTMLElement>('.quote-grid')?.setAttribute('hidden','');(document.querySelector('#export') as HTMLButtonElement).disabled=true;(document.querySelector('#pin') as HTMLButtonElement).disabled=true;}
}
function readForm(){for(const key of Object.keys(DEFAULTS) as (keyof Inputs)[]){const el=document.getElementById(key) as HTMLInputElement|null;if(el)state[key]=el.value.trim()===''?NaN:Number(el.value);}document.querySelectorAll('.preset').forEach(e=>e.classList.remove('chosen'));compute();}
function setState(i:Inputs){state={...i};for(const key of Object.keys(DEFAULTS) as (keyof Inputs)[]){const el=document.getElementById(key) as HTMLInputElement|null;if(el)el.value=String(state[key]);}compute();}
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.querySelector('#config-form')!.addEventListener('change',readForm);
document.querySelector('#config-form')!.addEventListener('submit',e=>{e.preventDefault();readForm();});
document.querySelectorAll<HTMLElement>('[data-preset]').forEach(b=>b.addEventListener('click',()=>{setState(PRESETS[Number(b.dataset.preset)].values);document.querySelectorAll('.preset').forEach(e=>e.classList.remove('chosen'));b.classList.add('chosen');}));
document.querySelector('#pin')!.addEventListener('click',()=>{readForm();if(current){baseline=current;render(current);notify('Current configuration pinned for comparison.');}});
document.querySelector('#reset')!.addEventListener('click',()=>{baseline=null;setState(DEFAULTS);});
document.querySelector('#export')!.addEventListener('click',()=>{readForm();if(current){download('curvescope-report.json',JSON.stringify(report(current),null,2));notify('Report exported with exact SDK values.');}});
document.addEventListener('input',e=>{const el=e.target as HTMLInputElement;if(el.tagName==='INPUT'&&el.id in DEFAULTS){document.querySelector('#valid-badge')!.textContent='Changes pending — recalculate';current=null;(document.querySelector('#export') as HTMLButtonElement).disabled=true;(document.querySelector('#pin') as HTMLButtonElement).disabled=true;}});
const file=document.querySelector<HTMLInputElement>('#file')!;
document.querySelector('#import')!.addEventListener('click',()=>file.click());
file.addEventListener('change',async()=>{try{if(file.files?.[0]){if(file.files[0].size>1e6)throw new Error('The file is too large. Maximum size is 1 MB.');setState(importReport(await file.files[0].text()));if(current)notify('Report imported and recalculated locally.');}}catch(e){notify(e instanceof Error?e.message:'Import failed.');}finally{file.value='';}});
compute();
